services:
  - type: web
    name: cobalt-api
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: API_URL
        sync: false

      - key: PORT
        value: "9000"
