services:

  - type: web
    name: cobalt-dpay
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./Dockerfile
    dockerContext: .

    envVars:

      - key: API_URL
        value: https://cobalt-dpay.onrender.com/

      - key: API_PORT
        value: "9000"

      - key: CORS_WILDCARD
        value: "1"

      - key: YOUTUBE_SESSION_SERVER
        sync: false


  - type: web
    name: yt-session-generator
    runtime: image
    plan: free
    region: singapore

    image:
      url: ghcr.io/imputnet/yt-session-generator:webserver

    healthCheckPath: /token
